os: linux
language: python
python: "3.6"

install:
  - pip install --upgrade pip
  - pip install -U -r requirements.txt
  - pip install pep8 pytest-pep8 pytest-xdist
  - pip install python-coveralls pytest-cov
  - cd ..
  - git clone https://github.com/GPflow/GPflow
  - cd GPflow
  - python setup.py install
  - cd ../SDCIT
  - ./setup.sh
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  - pytest --cov=sdcit --pep8

after_success:
  - coveralls