os:
  - linux
  - osx

language: python
python: "3.6"

install:
  - pip install pandas tqdm matplotlib seaborn joblib numpy scipy scikit-learn cython tensorflow
  - cd ..
  - git clone https://github.com/GPflow/GPflow
  - cd GPflow
  - python setup.py install
  - cd ../SDCIT
  - ./setup.sh
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  pytest
